#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend smartraysam-backend
        balance roundrobin
        server 333634-web-01 34.224.16.92:80 check
        server 333634-web-02 100.25.169.255:80 check
frontend smartraysam-frontend
        bind *:80
        mode http
        default_backend smartraysam-backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
