#!/usr/bin/env bash
# A Bash script that displays:
# To infinity and beyond indefinitely
# Sleep 2 in between the  loop
# I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
